package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.40

import (
	"context"
	"encoding/base64"
	"errors"
	"fmt"

	"github.com/kabece/gqlgen-chatroom/graph/generated"
	"github.com/kabece/gqlgen-chatroom/graph/model"
)

// GetSearchResultListings is the resolver for the getSearchResultListings field.
func (r *queryResolver) GetSearchResultListings(ctx context.Context, id string, filters *string, sort *string) (*model.SearchResultListings, error) {
	if t, ok := r.Results[id]; ok {
		t.Filters = *filters
		t.Sort = *sort
		return &t, nil
	}
	return nil, errors.New("results not found")
}

// LisitngsConnection is the resolver for the lisitngsConnection field.
func (r *searchResultListingsResolver) LisitngsConnection(ctx context.Context, obj *model.SearchResultListings, first *int, after *string) (*model.LisitngsConnection, error) {
	// The cursor is base64 encoded by convention, so we need to decode it first
	var decodedCursor string
	if after != nil {
		b, err := base64.StdEncoding.DecodeString(*after)
		if err != nil {
			return nil, err
		}
		decodedCursor = string(b)
	}

	// Here we could query the DB to get data, e.g. SELECT * FROM messages WHERE chat_room_id = obj.ID AND timestamp < decodedCursor
	// Mocking for now
	edges := make([]*model.ListingsEdge, *first)
	count := 0
	currentPage := false
	// If no cursor present start from the top
	if decodedCursor == "" {
		currentPage = true
	}
	hasNextPage := false

	// Iterating over the mocked listings to find the current page
	// In real world use-case you should fetch only the required part of data from the database
	for i, v := range r.Listings[obj.ID] {
		node := v

		if currentPage && count < *first {
			edges[count] = &model.ListingsEdge{
				Cursor: base64.StdEncoding.EncodeToString([]byte(v.ID)),
				Node:   &node,
			}
			count++
		}

		if v.ID == decodedCursor {
			currentPage = true
		}

		// If there are any elements left after the current page we indicate that in the response
		if count == *first && i < len(r.Listings[obj.ID]) {
			hasNextPage = true
		}
	}

	pageInfo := model.PageInfo{
		StartCursor: base64.StdEncoding.EncodeToString([]byte(edges[0].Node.ID)),
		EndCursor:   base64.StdEncoding.EncodeToString([]byte(edges[count-1].Node.ID)),
		HasNextPage: &hasNextPage,
	}

	fmt.Printf("LisitngsConnection | first: %v, pageInfo: %+v \n", *first, pageInfo)

	lc := model.LisitngsConnection{
		Edges:    edges[:count],
		PageInfo: &pageInfo,
	}

	return &lc, nil
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// SearchResultListings returns generated.SearchResultListingsResolver implementation.
func (r *Resolver) SearchResultListings() generated.SearchResultListingsResolver {
	return &searchResultListingsResolver{r}
}

type queryResolver struct{ *Resolver }
type searchResultListingsResolver struct{ *Resolver }
