// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type LisitngsConnection struct {
	Edges    []*ListingsEdge `json:"edges"`
	PageInfo *PageInfo       `json:"pageInfo"`
}

type Listing struct {
	ID    string  `json:"id"`
	Title *string `json:"title,omitempty"`
}

type ListingsEdge struct {
	Cursor string   `json:"cursor"`
	Node   *Listing `json:"node,omitempty"`
}

type PageInfo struct {
	StartCursor string `json:"startCursor"`
	EndCursor   string `json:"endCursor"`
	HasNextPage *bool  `json:"hasNextPage,omitempty"`
}
